/*
 * bro.java
 *
 * Created on November 15, 2022, 2:44 PM
 */


import admin.admin;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author  Bruce Elea
 */
public class bro extends javax.swing.JFrame {

    /** Creates new form bro */
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public bro() {
        initComponents();
        addItem();
    }

    private void getExtendedState(int MAXIMIZED_BOTH) {
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jblLOGIN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        tittle = new javax.swing.JComboBox();
        jblERASE = new javax.swing.JButton();
        jblEXIT = new javax.swing.JButton();
        jblSIGNUP = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        max = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        jblLOGIN.setFont(new java.awt.Font("Tahoma", 1, 18));
        jblLOGIN.setForeground(new java.awt.Color(0, 102, 102));
        jblLOGIN.setText("Login now");
        jblLOGIN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jblLOGIN.setContentAreaFilled(false);
        jblLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblLOGINActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("Username :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setText("Password :");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setText("Tittle :");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        password.setFont(new java.awt.Font("Tahoma", 1, 14));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Tahoma", 1, 14));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        tittle.setFont(new java.awt.Font("Tahoma", 1, 14));
        tittle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        tittle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tittleActionPerformed(evt);
            }
        });

        jblERASE.setFont(new java.awt.Font("Tahoma", 1, 18));
        jblERASE.setForeground(new java.awt.Color(0, 102, 102));
        jblERASE.setText("Reset");
        jblERASE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jblERASE.setContentAreaFilled(false);
        jblERASE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblERASEActionPerformed(evt);
            }
        });

        jblEXIT.setFont(new java.awt.Font("Tahoma", 1, 18));
        jblEXIT.setForeground(new java.awt.Color(0, 102, 102));
        jblEXIT.setText("Exit");
        jblEXIT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jblEXIT.setContentAreaFilled(false);
        jblEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblEXITActionPerformed(evt);
            }
        });

        jblSIGNUP.setFont(new java.awt.Font("Tahoma", 1, 18));
        jblSIGNUP.setForeground(new java.awt.Color(0, 102, 102));
        jblSIGNUP.setText("Signup");
        jblSIGNUP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jblSIGNUP.setContentAreaFilled(false);
        jblSIGNUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblSIGNUPActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 24));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        max.setFont(new java.awt.Font("Tahoma", 1, 14));
        max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        max.setText("[ ]");
        max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jblSIGNUP, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                        .addGap(77, 77, 77)
                                        .addComponent(jblERASE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tittle, 0, 204, Short.MAX_VALUE)
                                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jblEXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addComponent(jblLOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jblLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblSIGNUP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblEXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblERASE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jblSIGNUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblSIGNUPActionPerformed
signup s=new signup();
s.show();
dispose();// TODO add your handling code here:
}//GEN-LAST:event_jblSIGNUPActionPerformed

private void jblEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblEXITActionPerformed
this.setVisible(false);// TODO add your handling code here:
}//GEN-LAST:event_jblEXITActionPerformed

private void jblERASEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblERASEActionPerformed
username.setText(null);
password.setText(null);
tittle.setSelectedItem(null);
// TODO add your handling code here:
}//GEN-LAST:event_jblERASEActionPerformed

private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_passwordActionPerformed

private void jblLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblLOGINActionPerformed
   
    String Username = username.getText();   
    String Password = password.getText(); 
    String Tittle = tittle.getSelectedItem().toString();
    
    if(Username.isEmpty()||Password.isEmpty()||Tittle.isEmpty()){
    JOptionPane.showMessageDialog(null, "THE FIELDS MUST NOT BE EMPTY");    
    }
    
    else{
    
    try{
      Class.forName("com.mysql.jdbc.Driver");
          con=DriverManager.getConnection("jdbc:mysql://localhost:3306/red star", "root", "");
         String sql="Select * from login where username=? and password=? and tittle=?";
          pst= con.prepareStatement(sql);
         pst.setString(1, username.getText());
       pst.setString(2,password.getText());
       pst.setString(3, tittle.getSelectedItem().toString());
        rs=pst.executeQuery();
       
        if(rs.next()){
            
           String s1 =  rs.getString("Tittle");
           String un =  rs.getString("Username");
           if(Tittle.equalsIgnoreCase("Admin")&& s1.equalsIgnoreCase("admin"))
               
           {
               
           admin ad = new admin(Username);
           ad.setVisible(true);
           setVisible(false);
               
           }
           
           if(Tittle.equalsIgnoreCase("Manager")&& s1.equalsIgnoreCase("manager"))
               
           {
               
          admin ad = new admin(Username);
           ad.setVisible(true);
           setVisible(false);
               
               
           }
           
           if(Tittle.equalsIgnoreCase("Receptionist")&& s1.equalsIgnoreCase("receptionist"))
               
           {
               
           admin ad = new admin(Username);
           ad.setVisible(true);
           setVisible(false);
               
               
           }
           
           if(Tittle.equalsIgnoreCase("Cashier")&& s1.equalsIgnoreCase("cashier"))
               
           {
               
         admin ad = new admin(Username);
           ad.setVisible(true);
           setVisible(false);
               
           }
           
           if(Tittle.equalsIgnoreCase("Client")&& s1.equalsIgnoreCase("client"))
               
           {
               
           Home A=new Home();
           A.setVisible(true);
           setVisible(false);
               
           }
           
       }
       else{
           JOptionPane.showMessageDialog(null, "LOGIN FIELDS MISS MATCH");
           
           username.setText("");
           password.setText("");
           tittle.setSelectedItem("");
       } 
      con.close();
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    }
// TODO add your handling code here:
}//GEN-LAST:event_jblLOGINActionPerformed

private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
this.setState(JFrame.ICONIFIED);// TODO add your handling code here:
}//GEN-LAST:event_jLabel6MouseClicked

private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
System.exit(0);// TODO add your handling code here:
}//GEN-LAST:event_jLabel5MouseClicked

private void tittleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tittleActionPerformed

    
    
    // TODO add your handling code here:
}//GEN-LAST:event_tittleActionPerformed

private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
// TODO add your handling code here:
}//GEN-LAST:event_jPanel1ComponentResized

private void maxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseClicked
      if (this.getExtendedState()!= JFrame.MAXIMIZED_BOTH)
      {
        this.getExtendedState(JFrame.MAXIMIZED_BOTH);
      }
      else
      {
        this.getExtendedState(JFrame.NORMAL);
      }
      // TODO add your handling code here:
}//GEN-LAST:event_maxMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bro().setVisible(true);
            }
     });
    }
    public void addItem(){
         tittle.addItem("SELECT---");
         tittle.addItem("ADMIN");
         tittle.addItem("MANAGER");
         tittle.addItem("RECEPTIONIST");
         tittle.addItem("CASHIER");
         tittle.addItem("CLIENT");
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jblERASE;
    private javax.swing.JButton jblEXIT;
    private javax.swing.JButton jblLOGIN;
    private javax.swing.JButton jblSIGNUP;
    private javax.swing.JLabel max;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox tittle;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
